### ISSUE TITLE
Supported syntax differs from syntax on asciimath.org

### ISSUE THREAD

**Issue by lukasbestle** [runarberg/ascii2mathml#10]
I really like your library as it is well documented, quite fast and has a nice CLI. Previously I was using `mathjax-node`, but I want to switch for better performance.

While switching, I noticed that the syntax your library supports differs from the "official" one on the [AsciiMath website](http://asciimath.org/#syntax):

- [ ] The complex grouping brackets `abs`, `floor`, `ceil` and `norm` as well as the complex accents `overset`, `underset`, `ubrace`, `obrace`, `color` and `cancel` are not supported and are instead printed literally.
- [ ] Font commands are only recognized if the command is immediately followed by the quote that starts the string (i.e. `it"some text"`, not `it "some text"`). On asciimath.org there's a space in between.
- [ ] The name of the font commands differs. E.g. bold on asciimath.org is `bb`, which is double-struck in Ascii2MathML. To have bold text, I need to change it to `bf`.

Am I holding it wrong or what is the reason for the different syntax? Maybe you are following an entirely different spec?
In any case the addition of those features (especially the complex accents) would be amazing.

**Comment by runarberg** [comment]
@lukasbestle: Thanks for complimenting the library. While I started out with trying to write a clone of asciimath, there were a few syntax shortcomings that I noticed along the way. So I purposefully deviated from the “official” syntax along the way. Most notably was the support for over and underscript—which wasn’t supported while I was writing this—using `.^` and `._` (I wanted to use `^^` and `__` but `^^` was taken for the logical conjunction ‘∧’). Another short coming was the inability to control identifiers and operators which makes it sometimes impossible to write out some expressions—think writing down the [gamma distribution](https://en.wikipedia.org/wiki/Gamma_distribution), *Gamma*(*θ* | *α*, *β*), that includes both “Gamma” written down in latin letters, and the greek capital letter Gamma.

So when writing this library I decided to deviate a little from the syntax and offer full control over what gets mapped to identifiers (by surrounding backticks), operators (by a leading backslash), and numbers (by an octothorpe followed by surrounding backticks). I also—unlike the original—decided to try to be smart about unicode such that operation unicode characters (e.g. `∝`, `→`, `⏞`, etc.) get mapped to an `<mo>` tag. This means you can achieve `obrace(1+2+3+4)^("4 terms")` with the—albeit uglier—expression: `{: 1+2+3+4 :}.^⏞.^(4 "terms")`

That being said. I don’t necessarily oppose adding the complex grouping brackets. I think the only reason they are not there is that they were added after I wrote this library. Nor do I oppose fixing the `it "some text"` bug. I do however feel weird about mapping `bb` to boldface and `bbb` to blackboard fonts, that just feels wrong for some reason.

ps. Might I also add that I wrote this some time ago. Though I feel proud of it, it was my first and only compiler that I have ever written. I didn’t know anything about compilers at the time—not even that I was writing one—and I know very little about compilers now. So adding features and fixing bugs might be a little cumbersome. But you are welcome to give me a hand if you want to see this issue fixed 😉

**Comment by lukasbestle** [comment]
Thanks for your fast reply!

I see that a lot of thought went into the design of your "adapted" syntax, which is why I'm happy to migrate my current formulae (not that many at the moment) to your syntax. It turns out that most features I need are already supported (didn't know about your over- and underscript syntax, which is just fine for me).

I'm closing this issue because the general question is solved. I will take a look if I can fix/add some of the missing features that still make sense (i.e. those you don't have an alternative for) and send PRs for those.

**Comment by lukasbestle** [comment]
Done, see PRs #11, #12, #13 and #14.

By the way: While implementing the features I found out that you should update your Travis configuration to use more up-to-date Node versions and that you should upgrade your dependencies. The old versions of some of the tools you are using are deprecated, therefore building and tests only work with Node v4.

**Comment by lukasbestle** [comment]
Awesome, thanks! However the changelog is missing. Also you made changes to the README, but not to `gh-pages`.

**Comment by runarberg** [comment]
Thanks for notifying. I’ve updated both the `gh-pages` branch and `NEWS.md`. It’s been a while since I touch this repo, and I’ve changed workstations in the meantime 😉

**Comment by lukasbestle** [comment]
👍
