### ISSUE TITLE
req: Tilde urgently requested as accent

### ISSUE THREAD

**Issue by goessner** [runarberg/ascii2mathml#7]
I need tilde (~) as an accent (meaning perpendicular vectors), so I would like to kindly ask for that in one of the next versions.

Thanks

**Comment by runarberg** [comment]
@goessner Sure published. But you know you can always type `` `sin`.^~ `` or `f.^~` for an overscript in case you need another accent. The only difference is that the overscripted operator won’t have the `accent` attribute, which AFAICT has no visual significance.

**Comment by goessner** [comment]
thanks .. wasn't aware of that overscript trick.
